language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
before_script:
  - chmod 0777 ./node_modules/.bin/mocha
  - chmod 0777 ./node_modules/.bin/nyc
  - chmod 0777 ./node_modules/.bin/coveralls
services: mongodb

after_success: npm run coverage
